### ISSUE TITLE
Enable optional query parameters for settlements

### ISSUE THREAD

**Issue by bobmaerten** [Fintecture/fintecture-sdk-ruby#11]
In `settlements` endpoint (https://docs.fintecture.com/v2/#get-get-get-settlements and https://docs.fintecture.com/v2/#get-get-get-settlements-settlement_id) there are optional query params for filtering dates when fetching settlements and having detailed associated payments.

Those parameters cannot be used with current implementation of the PIS client and therefore is very limiting for daily usage.

**Comment by FcoRodrFintecture** [comment]
Hello @bobmaerten,

A new `include_payments` argument has been added to the `settlements` method in the `Fintecture::PisClient` class. If passed a `true` value, the associated payments details will be included.

You can find this in the new tagged minor version (0.4.0).

Regarding the dates filtering it's a documentation misalignment, as it is not an available feature, but it is in the scope of a future implementation.

Thanks for your feedback!

**Comment by bobmaerten** [comment]
Done in #12
