### ISSUE TITLE
Fix Fintecture::Pis::Connect.generate method arity

### ISSUE THREAD

**Issue by bless-you** [Fintecture/fintecture-sdk-ruby#26]
3 weeks ago you did [this change](https://github.com/Fintecture/fintecture-sdk-ruby/commit/78c9505214989d01de1a53d93dcf1ebe46f689e2#diff-d4d78baf253a7bdefa82030de63d31fb4262896b1e2ee9a2b90c138632c6e35bR45)

We faced an issue after upgrading gem to the latest version (0.6.0):
`lib/ruby/gems/3.2.0/gems/fintecture-0.6.0/lib/fintecture/api/pis/connect.rb:16:in 'generate': wrong number of arguments (given 6, expected 5) (ArgumentError)`

We are not 100% but at least it fixes the issue locally if you add double splash operator before `options`:
`lib/ruby/gems/3.2.0/gems/fintecture-0.6.0/lib/fintecture/pis_client.rb`

```suggestion
res = Fintecture::Pis::Connect.generate self, Marshal.load(Marshal.dump(payload)), state, redirect_uri, origin_uri, **options
```

**Comment by xlaumonier-fintecture** [comment]
@bless-you Good morning, we just released version 0.6.1. Please let us know if it resolves the issue. Thank you.
